books = [
    {
        "id": 1,
        "title": "Think Python",
        "author": "Allen B. Downey",
        "publisher": "O'Reilly Media",
        "published_date": "2021-01-01",
        "page_count": 1234,
        "language": "English",
    },
    {
        "id": 2,
        "title": "Django By Example",
        "author": "Antonio Mele",
        "publisher": "Packt Publishing Ltd",
        "published_date": "2022-01-19",
        "page_count": 1023,
        "language": "English",
    },
    {
        "id": 3,
        "title": "Fluent Python",
        "author": "Luciano Ramalho",
        "publisher": "O'Reilly Media",
        "published_date": "2022-03-15",
        "page_count": 1014,
        "language": "English",
    },
    {
        "id": 4,
        "title": "Python Crash Course",
        "author": "Eric Matthes",
        "publisher": "No Starch Press",
        "published_date": "2023-01-10",
        "page_count": 544,
        "language": "English",
    },
    {
        "id": 5,
        "title": "FastAPI in Action",
        "author": "Richard Hundt",
        "publisher": "Manning Publications",
        "published_date": "2023-08-29",
        "page_count": 376,
        "language": "English",
    },
    {
        "id": 6,
        "title": "Clean Code",
        "author": "Robert C. Martin",
        "publisher": "Prentice Hall",
        "published_date": "2008-08-11",
        "page_count": 464,
        "language": "English",
    },
    {
        "id": 7,
        "title": "The Pragmatic Programmer",
        "author": "Andrew Hunt",
        "publisher": "Addison-Wesley",
        "published_date": "2019-09-13",
        "page_count": 352,
        "language": "English",
    },
    {
        "id": 8,
        "title": "Designing Data-Intensive Applications",
        "author": "Martin Kleppmann",
        "publisher": "O'Reilly Media",
        "published_date": "2017-03-16",
        "page_count": 616,
        "language": "English",
    },
    {
        "id": 9,
        "title": "Learning Python",
        "author": "Mark Lutz",
        "publisher": "O'Reilly Media",
        "published_date": "2013-06-12",
        "page_count": 1648,
        "language": "English",
    },
    {
        "id": 10,
        "title": "Automate the Boring Stuff with Python",
        "author": "Al Sweigart",
        "publisher": "No Starch Press",
        "published_date": "2019-11-12",
        "page_count": 592,
        "language": "English",
    },
]